package com.example.e_commerce.view;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.widget.GridView;

import java.util.ArrayList;

import com.example.e_commerce.R;
import com.example.e_commerce.adapter.AllCategoryAdapter;
import com.example.e_commerce.model.AllCategory;


public class all_categories extends AppCompatActivity {
    GridView gridView;
    ArrayList<AllCategory> list;
    AllCategoryAdapter adapterGrid;
    int id;
    @Override

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_all_categories);
        gridView = findViewById(R.id.gridlayout);
        getWindow().setStatusBarColor(getResources().getColor(R.color.white,getTheme()));



        Intent intent = getIntent();
        id = intent.getIntExtra("id",-1);
        Log.d("idxx",String.valueOf(id));
        gridList();
        adapterGrid = new AllCategoryAdapter(this,list);
        gridView.setAdapter(adapterGrid);

//
    }
    private void gridList()
    {
        list = new ArrayList<AllCategory>();
        if(id==0) {
            list.add(new AllCategory("Fashion", R.drawable.chips1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Mobiles", R.drawable.chips2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Electronics", R.drawable.chips3, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Home", R.drawable.chips4, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Appliances", R.drawable.chips5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.chips6, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.chips7, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.chips8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.chips9, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
        }else if(id == 1){
            list.add(new AllCategory("Fashion", R.drawable.drinks1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Mobiles", R.drawable.drinks2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Electronics", R.drawable.drinks3, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Home", R.drawable.drinks4, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Appliances", R.drawable.drinks5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.drinks6, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.drinks7, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.drinks8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.drinks9, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
        } else if (id == 2) {
            list.add(new AllCategory("Fashion", R.drawable.foods1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Mobiles", R.drawable.foods2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Electronics", R.drawable.foods3, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Home", R.drawable.foods4, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Appliances", R.drawable.foods5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.foods6, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.foods7, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.foods8, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
            list.add(new AllCategory("Beauty", R.drawable.foods9, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu eros id est scelerisque scelerisque vel at sem. Sed in nibh ac est aliquet porttitor. Vestibulum vel orci nec justo vulputate facilisis. Nulla facilisi. Nulla et ex at ligula posuere accumsan nec eu nisl. Phasellus quis aliquet velit, a posuere urna. Maecenas dapibus, magna in venenatis posuere, sem quam volutpat neque, ac sodales elit nisl vel sapien. Suspendisse nec ultrices lacus.", "150"));
        }
    }

}